//! Deterministic, email-client-safe rendering for Task Session Feishu mail.
//!
//! Markdown is an authoring format only. This module never passes raw Markdown or raw HTML to
//! the mail client: unsupported HTML is displayed as text and only a small HTML allowlist is
//! generated by this renderer.

use serde::{Deserialize, Serialize};

const MAX_SUBJECT_CHARS: usize = 256;
const MAX_BODY_CHARS: usize = 100_000;
const MAX_RECIPIENTS: usize = 50;

#[derive(Debug, Clone, Deserialize)]
pub struct MailPrepareInput {
    pub to: Vec<String>,
    #[serde(default)]
    pub cc: Vec<String>,
    #[serde(default)]
    pub bcc: Vec<String>,
    pub subject: String,
    pub markdown: String,
    #[serde(default)]
    pub signature_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct RenderedMail {
    pub to: Vec<String>,
    pub cc: Vec<String>,
    pub bcc: Vec<String>,
    pub subject: String,
    pub html: String,
    pub preview_text: String,
    pub signature_id: Option<String>,
}

pub fn render_mail(input: MailPrepareInput) -> Result<RenderedMail, String> {
    let subject = normalize_subject(&input.subject)?;
    let markdown = input.markdown.trim();
    if markdown.is_empty() {
        return Err("邮件正文不能为空".to_string());
    }
    if markdown.chars().count() > MAX_BODY_CHARS {
        return Err(format!("邮件正文不能超过 {MAX_BODY_CHARS} 个字符"));
    }
    let signature_id = normalize_optional_token(input.signature_id.as_deref(), "signature_id")?;
    let to = normalize_addresses(&input.to, "to", true)?;
    let cc = normalize_addresses(&input.cc, "cc", false)?;
    let bcc = normalize_addresses(&input.bcc, "bcc", false)?;
    let (body_html, preview_text) = render_markdown(markdown);
    let html = format!(
        concat!(
            "<div style=\"padding:24px;",
            "font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;",
            "font-size:14px;line-height:1.65;color:#1f2329;\">",
            "{}</div>"
        ),
        body_html
    );
    Ok(RenderedMail {
        to,
        cc,
        bcc,
        subject,
        html,
        preview_text,
        signature_id,
    })
}

fn normalize_subject(value: &str) -> Result<String, String> {
    let value = value.trim();
    if value.is_empty() {
        return Err("邮件主题不能为空".to_string());
    }
    if value.contains(['\r', '\n']) {
        return Err("邮件主题不能包含换行".to_string());
    }
    if value.chars().count() > MAX_SUBJECT_CHARS {
        return Err(format!("邮件主题不能超过 {MAX_SUBJECT_CHARS} 个字符"));
    }
    Ok(value.to_string())
}

fn normalize_optional_token(value: Option<&str>, field: &str) -> Result<Option<String>, String> {
    let Some(value) = value.map(str::trim).filter(|value| !value.is_empty()) else {
        return Ok(None);
    };
    if value.chars().count() > 256 || value.contains(['\r', '\n', '\0']) {
        return Err(format!("{field} 格式无效"));
    }
    Ok(Some(value.to_string()))
}

fn normalize_addresses(
    values: &[String],
    field: &str,
    required: bool,
) -> Result<Vec<String>, String> {
    if values.len() > MAX_RECIPIENTS {
        return Err(format!("{field} 不能超过 {MAX_RECIPIENTS} 个收件人"));
    }
    let values = values
        .iter()
        .map(|value| value.trim())
        .filter(|value| !value.is_empty())
        .map(|value| {
            if !is_mail_address(value) {
                Err(format!("{field} 包含无效邮箱地址：{value}"))
            } else {
                Ok(value.to_string())
            }
        })
        .collect::<Result<Vec<_>, _>>()?;
    if required && values.is_empty() {
        return Err("至少需要一个收件人".to_string());
    }
    Ok(values)
}

fn is_mail_address(value: &str) -> bool {
    if value.len() > 319 || value.contains(char::is_whitespace) || value.contains(['\r', '\n']) {
        return false;
    }
    let Some((local, domain)) = value.rsplit_once('@') else {
        return false;
    };
    !local.is_empty() && !domain.is_empty() && !domain.starts_with('.') && !domain.ends_with('.')
}

fn render_markdown(markdown: &str) -> (String, String) {
    let lines = markdown.lines().collect::<Vec<_>>();
    let mut html = String::new();
    let mut plain = String::new();
    let mut index = 0;
    while index < lines.len() {
        let line = lines[index].trim_end();
        if line.trim().is_empty() {
            index += 1;
            continue;
        }
        if let Some((level, text)) = heading(line) {
            let text_html = render_inline(text);
            html.push_str(&format!(
                "<h{level} style=\"margin:24px 0 10px;font-size:{}px;line-height:1.35;color:#172b4d;\">{text_html}</h{level}>",
                match level { 1 => 22, 2 => 18, _ => 16 }
            ));
            push_plain_line(&mut plain, &plain_inline(text));
            index += 1;
            continue;
        }
        if line.starts_with("```") {
            let (next, code) = collect_code_block(&lines, index + 1);
            html.push_str("<pre style=\"margin:12px 0;padding:12px;background:#f5f6f7;border:1px solid #e5e6eb;border-radius:6px;white-space:pre-wrap;font-family:SFMono-Regular,Consolas,monospace;font-size:12px;line-height:1.55;\">");
            html.push_str(&escape_html(&code));
            html.push_str("</pre>");
            push_plain_line(&mut plain, &code);
            index = next;
            continue;
        }
        if is_table_start(&lines, index) {
            let (next, rows) = collect_table(&lines, index);
            render_table(&mut html, &mut plain, &rows);
            index = next;
            continue;
        }
        if let Some(item) = unordered_item(line) {
            let (next, items) = collect_list(&lines, index, false);
            html.push_str("<ul style=\"margin:8px 0 12px;padding-left:22px;\">");
            for item in &items {
                html.push_str(&format!(
                    "<li style=\"margin:4px 0;\">{}</li>",
                    render_inline(item)
                ));
                push_plain_line(&mut plain, &format!("• {}", plain_inline(item)));
            }
            html.push_str("</ul>");
            let _ = item;
            index = next;
            continue;
        }
        if ordered_item(line).is_some() {
            let (next, items) = collect_list(&lines, index, true);
            html.push_str("<ol style=\"margin:8px 0 12px;padding-left:22px;\">");
            for (number, item) in items.iter().enumerate() {
                html.push_str(&format!(
                    "<li style=\"margin:4px 0;\">{}</li>",
                    render_inline(item)
                ));
                push_plain_line(
                    &mut plain,
                    &format!("{}. {}", number + 1, plain_inline(item)),
                );
            }
            html.push_str("</ol>");
            index = next;
            continue;
        }
        let (next, paragraph) = collect_paragraph(&lines, index);
        html.push_str(&format!(
            "<p style=\"margin:0 0 12px;\">{}</p>",
            render_inline(&paragraph)
        ));
        push_plain_line(&mut plain, &plain_inline(&paragraph));
        index = next;
    }
    (html, plain.trim().to_string())
}

fn heading(line: &str) -> Option<(u8, &str)> {
    let count = line
        .chars()
        .take_while(|character| *character == '#')
        .count();
    (1..=3)
        .contains(&count)
        .then(|| {
            line.get(count..)
                .filter(|tail| tail.starts_with(' '))
                .map(str::trim)
        })
        .flatten()
        .filter(|text| !text.is_empty())
        .map(|text| (count as u8, text))
}

fn unordered_item(line: &str) -> Option<&str> {
    ["- ", "* ", "+ "]
        .iter()
        .find_map(|prefix| line.strip_prefix(prefix).map(str::trim))
        .filter(|item| !item.is_empty())
}

fn ordered_item(line: &str) -> Option<&str> {
    let digits = line
        .chars()
        .take_while(|character| character.is_ascii_digit())
        .count();
    (digits > 0)
        .then(|| {
            line.get(digits..)
                .and_then(|tail| tail.strip_prefix('.'))
                .map(str::trim)
        })
        .flatten()
        .filter(|item| !item.is_empty())
}

fn collect_list(lines: &[&str], start: usize, ordered: bool) -> (usize, Vec<String>) {
    let mut index = start;
    let mut items = Vec::new();
    while index < lines.len() {
        let item = if ordered {
            ordered_item(lines[index])
        } else {
            unordered_item(lines[index])
        };
        let Some(item) = item else { break };
        items.push(item.to_string());
        index += 1;
    }
    (index, items)
}

fn collect_code_block(lines: &[&str], mut index: usize) -> (usize, String) {
    let mut code = Vec::new();
    while index < lines.len() && !lines[index].trim_start().starts_with("```") {
        code.push(lines[index]);
        index += 1;
    }
    if index < lines.len() {
        index += 1;
    }
    (index, code.join("\n"))
}

fn is_table_start(lines: &[&str], index: usize) -> bool {
    lines.get(index).is_some_and(|line| line.contains('|'))
        && lines
            .get(index + 1)
            .is_some_and(|line| is_table_separator(line))
}

fn is_table_separator(line: &str) -> bool {
    let cells = split_table_row(line);
    !cells.is_empty()
        && cells.iter().all(|cell| {
            let cell = cell.trim_matches(':').trim();
            cell.len() >= 3 && cell.chars().all(|character| character == '-')
        })
}

fn collect_table(lines: &[&str], start: usize) -> (usize, Vec<Vec<String>>) {
    let mut rows = vec![split_table_row(lines[start])];
    let mut index = start + 2;
    while index < lines.len() && lines[index].contains('|') && !lines[index].trim().is_empty() {
        rows.push(split_table_row(lines[index]));
        index += 1;
    }
    (index, rows)
}

fn split_table_row(line: &str) -> Vec<String> {
    line.trim()
        .trim_matches('|')
        .split('|')
        .map(|cell| cell.trim().to_string())
        .collect()
}

fn render_table(html: &mut String, plain: &mut String, rows: &[Vec<String>]) {
    html.push_str("<table role=\"presentation\" style=\"width:100%;margin:12px 0;border-collapse:collapse;border:1px solid #d9dce1;\">");
    for (row_index, row) in rows.iter().enumerate() {
        html.push_str("<tr>");
        for cell in row {
            let tag = if row_index == 0 { "th" } else { "td" };
            let style = if row_index == 0 {
                "padding:8px 10px;border:1px solid #d9dce1;background:#f5f6f7;text-align:left;font-weight:600;"
            } else {
                "padding:8px 10px;border:1px solid #d9dce1;text-align:left;vertical-align:top;"
            };
            html.push_str(&format!(
                "<{tag} style=\"{style}\">{}</{tag}>",
                render_inline(cell)
            ));
        }
        html.push_str("</tr>");
        push_plain_line(
            plain,
            &row.iter()
                .map(|cell| plain_inline(cell))
                .collect::<Vec<_>>()
                .join(" | "),
        );
    }
    html.push_str("</table>");
}

fn collect_paragraph(lines: &[&str], start: usize) -> (usize, String) {
    let mut index = start;
    let mut paragraph = Vec::new();
    while index < lines.len() {
        let line = lines[index];
        if line.trim().is_empty()
            || (index != start
                && (heading(line).is_some()
                    || unordered_item(line).is_some()
                    || ordered_item(line).is_some()
                    || line.trim_start().starts_with("```")
                    || is_table_start(lines, index)))
        {
            break;
        }
        paragraph.push(line.trim());
        index += 1;
    }
    (index, paragraph.join("\n"))
}

fn render_inline(value: &str) -> String {
    let mut output = String::new();
    let mut remaining = value;
    while !remaining.is_empty() {
        if let Some(rest) = remaining.strip_prefix("**") {
            if let Some((content, tail)) = rest.split_once("**") {
                output.push_str("<strong>");
                output.push_str(&escape_html(content));
                output.push_str("</strong>");
                remaining = tail;
                continue;
            }
        }
        if let Some(rest) = remaining.strip_prefix('`') {
            if let Some((content, tail)) = rest.split_once('`') {
                output.push_str("<code style=\"padding:1px 4px;background:#f5f6f7;border-radius:3px;font-family:SFMono-Regular,Consolas,monospace;\">");
                output.push_str(&escape_html(content));
                output.push_str("</code>");
                remaining = tail;
                continue;
            }
        }
        if let Some(rest) = remaining.strip_prefix('[') {
            if let Some((label, after_label)) = rest.split_once("](") {
                if let Some((url, tail)) = after_label.split_once(')') {
                    if is_safe_link(url) {
                        output.push_str("<a style=\"color:#3370ff;text-decoration:none;\" href=\"");
                        output.push_str(&escape_html(url));
                        output.push_str("\">");
                        output.push_str(&escape_html(label));
                        output.push_str("</a>");
                        remaining = tail;
                        continue;
                    }
                }
            }
        }
        let character = remaining.chars().next().expect("non-empty remaining text");
        output.push_str(&escape_html(&character.to_string()));
        remaining = &remaining[character.len_utf8()..];
    }
    output.replace('\n', "<br>")
}

fn plain_inline(value: &str) -> String {
    let mut output = String::new();
    let mut remaining = value;
    while !remaining.is_empty() {
        if let Some(rest) = remaining.strip_prefix("**") {
            if let Some((content, tail)) = rest.split_once("**") {
                output.push_str(content);
                remaining = tail;
                continue;
            }
        }
        if let Some(rest) = remaining.strip_prefix('`') {
            if let Some((content, tail)) = rest.split_once('`') {
                output.push_str(content);
                remaining = tail;
                continue;
            }
        }
        if let Some(rest) = remaining.strip_prefix('[') {
            if let Some((label, after_label)) = rest.split_once("](") {
                if let Some((url, tail)) = after_label.split_once(')') {
                    output.push_str(label);
                    if is_safe_link(url) {
                        output.push_str(" (");
                        output.push_str(url);
                        output.push(')');
                    }
                    remaining = tail;
                    continue;
                }
            }
        }
        let character = remaining.chars().next().expect("non-empty remaining text");
        output.push(character);
        remaining = &remaining[character.len_utf8()..];
    }
    output
}

fn is_safe_link(value: &str) -> bool {
    let value = value.trim();
    value.starts_with("https://") || value.starts_with("http://") || value.starts_with("mailto:")
}

fn escape_html(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

fn push_plain_line(target: &mut String, line: &str) {
    if !target.is_empty() {
        target.push('\n');
    }
    target.push_str(line);
}

#[cfg(test)]
mod tests {
    use super::{render_mail, MailPrepareInput};

    fn input(markdown: &str) -> MailPrepareInput {
        MailPrepareInput {
            to: vec!["alice@example.com".to_string()],
            cc: Vec::new(),
            bcc: Vec::new(),
            subject: "记录摘要".to_string(),
            markdown: markdown.to_string(),
            signature_id: None,
        }
    }

    #[test]
    fn renders_supported_markdown_as_email_safe_html() {
        let rendered = render_mail(input("# 摘要\n\n- **完成** API\n- 访问 [文档](https://example.com)\n\n| 项目 | 状态 |\n| --- | --- |\n| 邮件 | 完成 |")).expect("rendered mail");
        assert!(rendered.html.contains("<h1"));
        assert!(rendered.html.contains("<strong>完成</strong>"));
        assert!(rendered.html.contains("href=\"https://example.com\""));
        assert!(rendered.html.contains("<table"));
        assert!(!rendered.html.contains("max-width:640px"));
        assert!(!rendered.html.contains("margin:0 auto"));
        assert_eq!(
            rendered.preview_text,
            "摘要\n• 完成 API\n• 访问 文档 (https://example.com)\n项目 | 状态\n邮件 | 完成"
        );
    }

    #[test]
    fn escapes_raw_html_and_rejects_unsafe_links() {
        let rendered = render_mail(input(
            "<script>alert(1)</script> [危险](javascript:alert(1))",
        ))
        .expect("rendered mail");
        assert!(rendered
            .html
            .contains("&lt;script&gt;alert(1)&lt;/script&gt;"));
        assert!(!rendered.html.contains("href=\"javascript:"));
    }

    #[test]
    fn validates_recipient_and_subject() {
        let mut invalid = input("正文");
        invalid.to = vec!["not-an-email".to_string()];
        assert!(render_mail(invalid).is_err());
        let mut invalid = input("正文");
        invalid.subject = "标题\nBcc: attacker@example.com".to_string();
        assert!(render_mail(invalid).is_err());
    }
}
